### Account erstellen
POST http://localhost:8084/user/create/account/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "ownerUserId" : "123e4567-e89b-12d3-a456-426614174000",
  "accountName": "Test",
  "currencyCode": "CHF"
}

### Alle Accounts eines Users abrufen
GET http://localhost:8084/user/123e4567-e89b-12d3-a456-426614174000/get/accounts
Accept: application/json


### Neue Cashflow-Transaktion erstellen
POST http://localhost:8084/api/v1/user/123e4567-e89b-12d3-a456-426614174000/account/8804aaec-e5bf-47fa-8f28-0be67563b33a/cashFlowTransaction
Content-Type: application/json

{
  "cashFlowDate": "2025-05-21T20:00:00",
  "accountId": "bfbee9f9-32fe-45be-b5bd-04845fd1a926",
  "userId": "123e4567-e89b-12d3-a456-426614174000",
  "cashFlowAmount": 1500.00,
  "cashFlowType": "DEPOSIT",
  "comment": "Initial Einzahlung"
}


### Neue Cashflow-Transaktion erstellen
POST http://localhost:8084/api/v1/user/account/cashFlowTransaction
Content-Type: application/json

{
  "cashFlowDate": "2025-05-21T20:00:00",
  "accountId": "bfbee9f9-32fe-45be-b5bd-04845fd1a926",
  "userId": "123e4567-e89b-12d3-a456-426614174000",
  "cashFlowAmount": 350.00,
  "cashFlowType": "DEPOSIT",
  "comment": "Auszahlung"
}

###
POST http://localhost:8084/api/v1/user/123e4567-e89b-12d3-a456-426614174000/account/8804aaec-e5bf-47fa-8f28-0be67563b33a/cashFlowTransaction
Content-Type: application/json

{
    "cashFlowDate": "2025-05-21T20:00:00",
    "accountId": "bfbee9f9-32fe-45be-b5bd-04845fd1a926",
    "userId": "123e4567-e89b-12d3-a456-426614174000",
    "cashFlowAmount": 1500.00,
    "cashFlowType": "DIVIDEND_PAYMENT",
    "comment": "Auszahlung "
}

###


GET http://localhost:8084/api/v1/user/123e4567-e89b-12d3-a456-426614174000/get/account/bfbee9f9-32fe-45be-b5bd-04845fd1a926
Content-Type: application/json